---

########################################################################
# Generate migration Jenkins jobs.
########################################################################

- name: Create a list of AEM Upgrade jobs for AWS
  shell: echo {{ item.path }}
  with_filetree: ../../../provisioners/jenkins/jenkinsfiles/aem-opencloud/migration/aws/
  when: item.state == 'file' and item.path is match('.*aem-upgrade')
  register: migration_aem_upgrade_jobs

- name: Create a list of AEM Reconfiguration jobs for AWS
  shell: echo {{ item.path }}
  with_filetree: ../../../provisioners/jenkins/jenkinsfiles/aem-opencloud/migration/aws/
  when: item.state == 'file' and item.path is match('.*aem-reconfiguration')
  register: migration_aem_reconfiguration_jobs

- name: "Generate AEM OpenCloud Jenkins jobs for AEM upgrade migration configuration profile directories"
  file:
    path: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/migration/aws/{{ item[0].item.path }}-{{ item[2].item.path }}/{{ item[1].item.path }}/
    state: directory
    mode: '0776'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_upgrade_profiles.results }}"
    - "{{ migration_aem_upgrade_jobs.results }}"
    - "{{ aem_stack_manager_messenger_profiles.results }}"
  when: item[0].skipped is not defined and item[0].item.skipped is not defined and item[1].skipped is not defined and item[1].item.skipped is not defined and item[2].skipped is not defined and item[2].item.skipped is not defined

- name: "Generate AEM OpenCloud Jenkins jobs for AEM reconfiguration migration configuration profile directories"
  file:
    path: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/migration/aws/{{ item[0].item.path }}-{{ item[2].item.path }}/{{ item[1].item.path }}/
    state: directory
    mode: '0776'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_reconfiguration_profiles.results }}"
    - "{{ migration_aem_reconfiguration_jobs.results }}"
    - "{{ aem_stack_manager_messenger_profiles.results }}"
  when: item[0].skipped is not defined and item[0].item.skipped is not defined and item[1].skipped is not defined and item[1].item.skipped is not defined and item[2].skipped is not defined and item[2].item.skipped is not defined

- name: "Generate AEM OpenCloud Jenkins jobs for AEM upgrade migration configuration profile config.xml for AEM upgrade migration configuration profile components"
  template:
    src: '../../../templates/ansible/jenkins/config/category-config-profile.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/migration/aws/{{ item[0].item.path }}-{{ item[2].item.path }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_upgrade_profiles.results }}"
    - "{{ migration_aem_upgrade_jobs.results }}"
    - "{{ aem_stack_manager_messenger_profiles.results }}"
  when: item[0].skipped is not defined and item[0].item.skipped is not defined and item[1].skipped is not defined and item[1].item.skipped is not defined and item[2].skipped is not defined and item[2].item.skipped is not defined

- name: "Generate AEM OpenCloud Jenkins jobs for AEM reconfiguration configuration profile config.xml for AEM upgrade migration configuration profile components"
  template:
    src: '../../../templates/ansible/jenkins/config/category-config-profile.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/migration/aws/{{ item[0].item.path }}-{{ item[2].item.path }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_reconfiguration_profiles.results }}"
    - "{{ migration_aem_reconfiguration_jobs.results }}"
    - "{{ aem_stack_manager_messenger_profiles.results }}"
  when: item[0].skipped is not defined and item[0].item.skipped is not defined and item[1].skipped is not defined and item[1].item.skipped is not defined and item[2].skipped is not defined and item[2].item.skipped is not defined

- name: "Generate AEM OpenCloud Jenkins jobs for AEM upgrade migration config.xml for AEM upgrade migration configuration profile components"
  template:
    src: ../../../templates/ansible/jenkins/config/jobs-migration-aem-upgrade.xml.j2
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/migration/aws/{{ item[0].item.path }}-{{ item[2].item.path }}/{{ item[1].item.path }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_upgrade_profiles.results }}"
    - "{{ migration_aem_upgrade_jobs.results }}"
    - "{{ aem_stack_manager_messenger_profiles.results }}"
  when: item[0].skipped is not defined and item[0].item.skipped is not defined and item[1].skipped is not defined and item[1].item.skipped is not defined and item[2].skipped is not defined and item[2].item.skipped is not defined

- name: "Generate AEM OpenCloud Jenkins jobs for AEM reconfiguration config.xml for AEM upgrade migration configuration profile components"
  template:
    src: ../../../templates/ansible/jenkins/config/jobs-migration-aem-reconfiguration.xml.j2
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/migration/aws/{{ item[0].item.path }}-{{ item[2].item.path }}/{{ item[1].item.path }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_reconfiguration_profiles.results }}"
    - "{{ migration_aem_reconfiguration_jobs.results }}"
    - "{{ aem_stack_manager_messenger_profiles.results }}"
  when: item[0].skipped is not defined and item[0].item.skipped is not defined and item[1].skipped is not defined and item[1].item.skipped is not defined and item[2].skipped is not defined and item[2].item.skipped is not defined
