---
AWSTemplateFormatVersion: "2010-09-09"

Description: Create Instance Profile for running AEM OpenCloud Manager build pipelines

Resources:

  PackerAemArtefactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: aem-opencloud

  PackerAemBucketPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
        - Action: ['s3:GetObject', 's3:ListBucket']
          Effect: Allow
          Resource:
          - !Join ['', ['arn:aws:s3:::', !Ref 'PackerAemArtefactBucket']]
      PolicyName: PackerAemBucketPolicy
      Roles: [!Ref 'PackerAemRole']


  PackerAemRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: PackerAemRolePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - acm:GetCertificate
                  - ec2:AttachVolume
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:CopyImage
                  - ec2:CreateImage
                  - ec2:CreateKeypair
                  - ec2:CreateSecurityGroup
                  - ec2:CreateSnapshot
                  - ec2:CreateTags
                  - ec2:CreateVolume
                  - ec2:DeleteKeypair
                  - ec2:DeleteSecurityGroup
                  - ec2:DeleteSnapshot
                  - ec2:DeleteVolume
                  - ec2:DeregisterImage
                  - ec2:DescribeImageAttribute
                  - ec2:DescribeImages
                  - ec2:DescribeInstances
                  - ec2:DescribeRegions
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeSnapshots
                  - ec2:DescribeSubnets
                  - ec2:DescribeTags
                  - ec2:DescribeVolumes
                  - ec2:DetachVolume
                  - ec2:GetPasswordData
                  - ec2:ModifyImageAttribute
                  - ec2:ModifyInstanceAttribute
                  - ec2:ModifySnapshotAttribute
                  - ec2:RegisterImage
                  - ec2:RunInstances
                  - ec2:StopInstances
                  - ec2:TerminateInstances
                  - iam:PassRole
                  - kms:Decrypt
                  - secretsmanager:GetSecretValue
                  - ssm:GetParameterHistory
                  - ssm:GetParametersByPath
                  - ssm:GetParameters
                  - ssm:GetParameter
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:*
                Resource:
                  - arn:aws:logs:*:*:*


  PackerAemInstanceProfile:
      Type: AWS::IAM::InstanceProfile
      Properties:
        Path: /
        Roles:
          - Ref: PackerAemRole

  AemAwsStackBuilderRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: AemAwsStackBuilderRolePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - acm:*
                  - autoscaling:AttachInstances
                  - autoscaling:AttachLoadBalancerTargetGroups
                  - autoscaling:AttachLoadBalancers
                  - autoscaling:BatchDeleteScheduledAction
                  - autoscaling:BatchPutScheduledUpdateGroupAction
                  - autoscaling:CompleteLifecycleAction
                  - autoscaling:CreateAutoScalingGroup
                  - autoscaling:CreateLaunchConfiguration
                  - autoscaling:CreateOrUpdateTags
                  - autoscaling:DeleteAutoScalingGroup
                  - autoscaling:DeleteLaunchConfiguration
                  - autoscaling:DeleteLifecycleHook
                  - autoscaling:DeleteNotificationConfiguration
                  - autoscaling:DeletePolicy
                  - autoscaling:DeleteScheduledAction
                  - autoscaling:DeleteTags
                  - autoscaling:DescribeAccountLimits
                  - autoscaling:DescribeAdjustmentTypes
                  - autoscaling:DescribeAutoScalingGroups
                  - autoscaling:DescribeAutoScalingInstances
                  - autoscaling:DescribeAutoScalingNotificationTypes
                  - autoscaling:DescribeLaunchConfigurations
                  - autoscaling:DescribeLifecycleHookTypes
                  - autoscaling:DescribeLifecycleHooks
                  - autoscaling:DescribeLoadBalancerTargetGroups
                  - autoscaling:DescribeLoadBalancers
                  - autoscaling:DescribeMetricCollectionTypes
                  - autoscaling:DescribeNotificationConfigurations
                  - autoscaling:DescribePolicies
                  - autoscaling:DescribeScalingActivities
                  - autoscaling:DescribeScalingProcessTypes
                  - autoscaling:DescribeScheduledActions
                  - autoscaling:DescribeTags
                  - autoscaling:DescribeTerminationPolicyTypes
                  - autoscaling:DetachInstances
                  - autoscaling:DetachLoadBalancerTargetGroups
                  - autoscaling:DetachLoadBalancers
                  - autoscaling:DisableMetricsCollection
                  - autoscaling:EnableMetricsCollection
                  - autoscaling:EnterStandby
                  - autoscaling:ExitStandby
                  - autoscaling:PutLifecycleHook
                  - autoscaling:PutNotificationConfiguration
                  - autoscaling:PutScalingPolicy
                  - autoscaling:PutScheduledUpdateGroupAction
                  - autoscaling:RecordLifecycleActionHeartbeat
                  - autoscaling:ResumeProcesses
                  - autoscaling:SetDesiredCapacity
                  - autoscaling:SetInstanceHealth
                  - autoscaling:SetInstanceProtection
                  - autoscaling:SuspendProcesses
                  - autoscaling:TerminateInstanceInAutoScalingGroup
                  - autoscaling:UpdateAutoScalingGroup
                  - cloudformation:CreateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeStackResources
                  - cloudformation:DescribeStacks
                  - cloudformation:GetStackPolicy
                  - cloudformation:GetTemplate
                  - cloudformation:GetTemplateSummary
                  - cloudformation:ListStackResources
                  - cloudformation:ListStacks
                  - cloudformation:UpdateStack
                  - cloudwatch:DeleteAlarms
                  - cloudwatch:DescribeAlarmHistory
                  - cloudwatch:DescribeAlarms
                  - cloudwatch:DescribeAlarmsForMetric
                  - cloudwatch:GetDashboard
                  - cloudwatch:GetMetricData
                  - cloudwatch:GetMetricStatistics
                  - cloudwatch:GetMetricWidgetImage
                  - cloudwatch:ListDashboards
                  - cloudwatch:ListMetrics
                  - cloudwatch:PutMetricAlarm
                  - cloudwatch:PutMetricData
                  - dynamodb:BatchGetItem
                  - dynamodb:ConditionCheckItem
                  - dynamodb:CreateTable
                  - dynamodb:DeleteTable
                  - dynamodb:DescribeBackup
                  - dynamodb:DescribeContinuousBackups
                  - dynamodb:DescribeGlobalTable
                  - dynamodb:DescribeGlobalTableSettings
                  - dynamodb:DescribeLimits
                  - dynamodb:DescribeReservedCapacity
                  - dynamodb:DescribeReservedCapacityOfferings
                  - dynamodb:DescribeStream
                  - dynamodb:DescribeTable
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:GetItem
                  - dynamodb:GetRecords
                  - dynamodb:GetShardIterator
                  - dynamodb:ListBackups
                  - dynamodb:ListGlobalTables
                  - dynamodb:ListStreams
                  - dynamodb:ListTables
                  - dynamodb:ListTagsOfResource
                  - dynamodb:PutItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:UpdateItem
                  - dynamodb:UpdateTimeToLive
                  - ec2:AttachVolume
                  - ec2:AuthorizeSecurityGroupEgress
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:CopyImage
                  - ec2:CreateImage
                  - ec2:CreateKeyPair
                  - ec2:CreateKeyPair
                  - ec2:CreateSecurityGroup
                  - ec2:CreateSnapshot
                  - ec2:CreateTags
                  - ec2:CreateVolume
                  - ec2:DeleteKeyPair
                  - ec2:DeleteKeyPair
                  - ec2:DeleteSecurityGroup
                  - ec2:DeleteSnapshot
                  - ec2:DeleteVolume
                  - ec2:DeregisterImage
                  - ec2:DescribeAccountAttributes
                  - ec2:DescribeAvailabilityZones
                  - ec2:DescribeImageAttribute
                  - ec2:DescribeImages
                  - ec2:DescribeInstances
                  - ec2:DescribeKeyPairs
                  - ec2:DescribeKeyPairs
                  - ec2:DescribeRegions
                  - ec2:DescribeSecurityGroupReferences
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeSnapshots
                  - ec2:DescribeSubnets
                  - ec2:DescribeTags
                  - ec2:DescribeVolumes
                  - ec2:DescribeVpcs
                  - ec2:DetachVolume
                  - ec2:GetPasswordData
                  - ec2:ImportKeyPair
                  - ec2:ModifyImageAttribute
                  - ec2:ModifyInstanceAttribute
                  - ec2:ModifySnapshotAttribute
                  - ec2:RegisterImage
                  - ec2:RevokeSecurityGroupEgress
                  - ec2:RevokeSecurityGroupIngress
                  - ec2:RunInstances
                  - ec2:StopInstances
                  - ec2:TerminateInstances
                  - elasticloadbalancing:*
                  - events:DeleteRule
                  - events:DescribeRule
                  - events:PutRule
                  - events:PutTargets
                  - events:RemoveTargets
                  - iam:AddRoleToInstanceProfile
                  - iam:AttachRolePolicy
                  - iam:CreateInstanceProfile
                  - iam:CreatePolicy
                  - iam:CreateRole
                  - iam:CreateServiceLinkedRole
                  - iam:DeleteInstanceProfile
                  - iam:DeleteRole
                  - iam:DeleteRolePolicy
                  - iam:DetachRolePolicy
                  - iam:DeletePolicy
                  - iam:GetPolicy
                  - iam:GetRole
                  - iam:ListPolicyVersions
                  - iam:PassRole
                  - iam:PutRolePolicy
                  - iam:RemoveRoleFromInstanceProfile
                  - iam:UploadServerCertificate
                  - kms:Decrypt
                  - lambda:AddPermission
                  - lambda:CreateAlias
                  - lambda:CreateFunction
                  - lambda:DeleteAlias
                  - lambda:DeleteFunction
                  - lambda:GetFunction
                  - lambda:ListVersionsByFunction
                  - lambda:PublishVersion
                  - lambda:RemovePermission
                  - route53:ChangeResourceRecordSets
                  - route53:CreateHostedZone
                  - route53:DeleteHostedZone
                  - route53:GetChange
                  - route53:GetHostedZone
                  - route53:ListHostedZones
                  - route53:ListHostedZonesByName
                  - route53:ListResourceRecordSets
                  - s3:*
                  - sdb:DeleteDomain
                  - secretsmanager:CreateSecret
                  - secretsmanager:GetSecretValue
                  - secretsmanager:TagResource
                  - sns:CreateTopic
                  - sns:DeleteTopic
                  - sns:GetTopicAttributes
                  - sns:ListTopics
                  - sns:Publish
                  - sns:SetTopicAttributes
                  - sns:Subscribe
                  - sns:Unsubscribe
                  - sqs:CreateQueue
                  - sqs:DeleteQueue
                  - sqs:GetQueueAttributes
                  - sqs:ListQueues
                  - sqs:ReceiveMessage
                  - sqs:SetQueueAttributes
                  - ssm:AddTagsToResource
                  - ssm:CreateDocument
                  - ssm:DeleteDocument
                  - ssm:DescribeDocument
                  - ssm:GetParameter
                  - ssm:GetParameterHistory
                  - ssm:GetParameters
                  - ssm:GetParametersByPath
                  - ssm:PutParameter
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:*
                Resource:
                  - arn:aws:logs:*:*:*

  AemAwsStackBuilderInstanceProfile:
      Type: AWS::IAM::InstanceProfile
      Properties:
        Path: /
        Roles:
          - Ref: AemAwsStackBuilderRole
